# 配置文件示例

# 设置批处理大小
# 默认值为100,
# batch size = batch_size * gpu counts in ddp
batch_size = 25
learning_rate = 0.0001
datastr = 'tartanair'

# useless in ddp 
# worker_num = 4

# 是否只使用光流
# 加快数据集加载速度
# Stage 1 训练用不到RGB图像
flow_only = false
rcr_type = "NORCR"
shuffle = true

# 图像的宽度和高度
image_width = 640  
image_height = 448 


total_iterations = 5000
train_path = "data/test.txt"
val_path = "data/test.txt"
pretrained_model_path = ""
save_path = "checkpoints/test"
summary_path = "logs/test"