# 配置文件示例

# 设置批处理大小
# 默认值为100,
# batch size = batch_size * gpu counts in ddp
batch_size = 16
learning_rate = 0.0001
lambda_flow = 0.01
datastr = 'tartanair'

# useless in ddp 
# worker_num = 4

# 是否只使用光流
# 加快数据集加载速度
# Stage 1 训练用不到RGB图像
flow_only = false
rcr_type = "RCR"
shuffle = true

# 图像的宽度和高度
image_width = 640  
image_height = 448 


total_iterations = 50000
train_path = "data/train_pose.txt"
val_path = "data/val_pose.txt"
pretrained_model_path = "checkpoints/whole_rcr_lambda_1/init.pth"
save_path = "checkpoints/whole_rcr_lambda_001"
summary_path = "logs/whole_rcr_lambda_001"